"""metadatos de pagina: creador, descripcion, imagen de cabecera

Revision ID: 8ec2d1ce7651
Revises: c130a7046dd6
Create Date: 2026-08-08 18:37:22.292259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec2d1ce7651'
down_revision = 'c130a7046dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('header_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'header_image_path')
    op.drop_column('pages', 'description')
    op.drop_column('pages', 'created_by')
    # ### end Alembic commands ###
